# Copyright (c) 2018, ARM Limited.
# SPDX-License-Identifier: Apache-2.0

FROM arm64v8/ubuntu:bionic

COPY ./qemu-user-static/* /usr/bin/

# Set timezone
RUN echo 'Etc/UTC' > /etc/timezone && \
    ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
    apt-get update && apt-get install -q -y tzdata && \
    rm -rf /var/lib/apt/lists/*

RUN apt update && apt install -y \
    pkg-config \
    lsb-release \
    curl \
    bash-completion \
    gnupg2

ENV LANG en_US.UTF-8
ENV LC_ALL C.UTF-8

RUN curl http://repo.ros2.org/repos.key | apt-key add -
RUN sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main \
    `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'

ENV ROS_DISTRO crystal
RUN apt-get update && apt-get install -y \
    ros-$ROS_DISTRO-desktop && \
    rm -rf /var/lib/apt/lists/*
