
FROM ros2_cc_base
LABEL maintainer="Alberto Soragna asoragna at irobot dot com"


###### INSTALL RASPBIAN CROSS-COMPILATION REQUIREMENTS

# install gcc6 compiler and toolchain
RUN apt-get update && apt-get install -y \
  gcc-6 \
  g++-6 \
  g++-6-arm-linux-gnueabihf
