version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.7
  install:
    # Install requirements as system packages using pip
    - requirements: docs/requirements.txt
    # Ensure sphinx-build is in PATH
    - method: setuptools
      path: docs/sphinx_build_symlink/
    # Install ros_cross_compile using setuptools
    - method: setuptools
      path: .
