# Build the package under test from source, and all its dependencies, then run
# the tests of the package under test.
addons:
  apt:
    sources:
    - sourceline: 'deb http://packages.ros.org/ros2/ubuntu bionic main'
      key_url: 'https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc'
    packages:
    - curl
    - python-rosdep
    - python3-colcon-common-extensions
    - python3-vcstool
    # Fast-RTPS dependencies
    - libasio-dev
    - libtinyxml2-dev
    update: true
before_script:
- sudo rosdep init
- rosdep update
branches:
  only:
  - master
cache: apt
dist: bionic
git:
  clone: false
language: generic
script:
- mkdir -p ~/ros2_latest_cross_compile_ws/src
- cd ~/ros2_latest_cross_compile_ws
- curl https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos | vcs import src/
# Travis doesn't automatically switch between $TRAVIS_BRANCH and $TRAVIS_PULL_REQUEST_BRANCH
# so we explicitly state which branch to use in the CI run.
- BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
# The repo file for the repository needs to be generated on-the-fly to incorporate the
# custom repository URL and branch name, when a PR is being built.
- |
  vcs import src/ << EOF
  repositories:
    cross_compile:
      type: git
      url: "https://github.com/${TRAVIS_REPO_SLUG}.git"
      version: "${BRANCH}"
  EOF
# RTI_NC_LICENSE_ACCEPTED avoids the interactive prompt asking to accept the
# RTI Connext license.
# For "latest" builds, rosdep often misses some keys, adding "|| true", to
# ignore those failures, as it is often non-critical.
- RTI_NC_LICENSE_ACCEPTED=yes rosdep install -r --from-paths src --ignore-src --rosdistro eloquent -y || true
- colcon build --event-handlers console_cohesion+ --packages-up-to cross_compile --symlink-install
- colcon test --event-handlers console_cohesion+ --packages-select cross_compile --return-code-on-test-failure
sudo: true
