# Build the package under test from source, and all its dependencies, then run
# the tests of the package under test.
addons:
  apt:
    sources:
      - sourceline: 'deb http://packages.ros.org/ros2/ubuntu bionic main'
        key_url: 'https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc'
    packages:
      - curl
      - python-rosdep
      - python3-colcon-common-extensions
      - python3-vcstool
      # Fast-RTPS dependencies
      - libasio-dev
      - libtinyxml2-dev
    update: true
before_script:
  - sudo rosdep init
  - rosdep update
branches:
  only:
  - master
  - dashing-devel
cache: apt
dist: bionic
language: generic
script:
  - bash ./travis/run_travis_build
sudo: true
