
# Copyright (c) 2018, ARM Limited.
# SPDX-License-Identifier: Apache-2.0

FROM arm64v8/ubuntu:bionic

RUN apt-get update && apt-get install -y \
  liblog4cxx-dev \
  libtinyxml-dev \
  libtinyxml2-dev \
  libeigen3-dev \
  python3-dev \
  python3-numpy

# transform absolute simbolic links into relative ones
RUN apt-get install -y symlinks && symlinks -cr /lib /etc /opt /usr
