name: Run shellcheck linter
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Run Shellcheck on shell scripts
        uses: reviewdog/action-shellcheck@v1
